apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: web
    - name: jmeter-port
      port: 1099
      targetPort: 1099
    - name: ssh
      port: 22
      targetPort: 22
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: webstatus
      port: 8091
      targetPort: 8091
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: bartleonid/jmeter-slave
          ports:
            - containerPort: 80
            - containerPort: 1099
            - containerPort: 8091
            - containerPort: 22
            - containerPort: 4369
            - containerPort: 9001
            - containerPort: 9002
            - containerPort: 9003
            - containerPort: 9004
            - containerPort: 9005
            - containerPort: 9006
            - containerPort: 9007
            - containerPort: 9008
            - containerPort: 9009
            - containerPort: 9010
            - containerPort: 9011
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
          # command: ["bash"]
          # args:
          #   [
          #     "-c",
          #     "/opt/apache-jmeter-5.1/bin/jmeter -n -t /opt/apache-jmeter-5.1/bin/jmx/test.jmx -R nginx.default.svc.cluster.local",
          #   ]
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
